default: &default
  host: db
  user: root
  password: root
  adapter: postgres
  migration_files_path: db/migrations

development:
  <<: *default
  db: mydb
# test:
#   <<: *default
#   db: application_database_name_test

# production:
#   <<: *default
#   db: application_database_name_production
