version: "3.8"

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./multiverse_travel_booker_api:/home/crystal/app
    networks:
      - crystal_network
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db-milenio
    volumes:
      - ./multiverse_travel_booker_api/db/dbDataPsql:/var/lib/postgresql/data
    networks:
      - crystal_network

networks:
  crystal_network:
    driver: bridge
